#! /bin/sh

root=$PWD

pass=$(ls | grep pass)
crash=$(ls | grep crash)
wrongcode=$(ls | grep wrongcode)


num=0
id=1
for i in $pass
do
    echo $i
    if [ $num -lt 13132 ]
    then
        echo ./train/pass.${id}.feature
        mv $i ./train/pass.${id}.feature
        num=$(($num+1))
        id=$(($id+1))
    else
        if [ $num -eq 13132 ]
        then
            id=0
        fi
        echo ./test/pass.${id}.feature
        mv $i ./test/pass.${id}.feature
        num=$(($num+1))
        id=$(($id+1))
    fi
done


num=0
fail_id_train=1
fail_id_test=1
for i in $crash
do
    echo $i
    if [ $num -lt 6930 ]
    then
        echo ./train/fail.${fail_id_train}.feature
        mv $i ./train/fail.${fail_id_train}.feature
        num=$(($num+1))
        fail_id_train=$(($fail_id_train+1))
    else
        echo ./test/fail.${fail_id_test}.feature
        mv $i ./test/fail.${fail_id_test}.feature
        num=$(($num+1))
        fail_id_test=$(($fail_id_test+1))
    fi
done


num=0
for i in $wrongcode
do
    echo $i
    if [ $num -lt 70 ]
    then
        echo ./train/fail.${fail_id_train}.feature
        mv $i ./train/fail.${fail_id_train}.feature
        num=$(($num+1))
        fail_id_train=$(($fail_id_train+1))
    else
        echo ./test/fail.${fail_id_test}.feature
        mv $i ./test/fail.${fail_id_test}.feature
        num=$(($num+1))
        fail_id_test=$(($fail_id_test+1))
    fi
done

